apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jvo5rv8l2-python 
  janus-idp.io/tekton: jvo5rv8l2-python
  backstage.io/kubernetes-id: jvo5rv8l2-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jvo5rv8l2-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml