apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jvo5rv8l2-python-gitops
  description: This is GitOps manifest for jvo5rv8l2-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=jvo5rv8l2-python
    backstage.io/kubernetes-id: jvo5rv8l2-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: jvo5rv8l2-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jvo5rv8l2-python
